### ISSUE TITLE
Updated to 0.3.0 but all nodes are missing

### ISSUE THREAD

**Issue by flamingm0e** [AYapejian/node-red-contrib-home-assistant#38] opened 2018-02-18 04:13 UTC
I just updated to 0.3.0 and after restarting Node Red, all home assistant nodes are missing from all my flows, and from the left hand side.  They still show as being installed, but none of my flows are working now.
![screenshot from 2018-02-17 22-10-04](https://user-images.githubusercontent.com/1229798/36348184-c35852e6-142f-11e8-9ba4-6b06d562ce1d.png)

**Comment by flamingm0e** [comment] 2018-02-18 04:22
Just threw another node-red docker up and installed a fresh home-assistant node, and it worked fine.  I will try to uninstall from the 'production' instance and install a fresh HA node

**Comment by flamingm0e** [comment] 2018-02-18 04:30
No go.  I cannot update to 0.3.0 on my 'production instance'

**Comment by impulz** [comment] 2018-02-18 07:57
I'm having the same problem with a freshly installed hass.io System. 
I installed hass.io (1.1) with Home Assistant (0.63.2), added the Node-Red Plugin (0.1.8) and installed the node-red-contrib-home-assistant (0.3.0) palette. The nodes were visible first but on deployment I received multiple errors saying the nodes are not installed. 

The Node-Red log shows the following errors during startup:

Welcome to Node-RED
===================
18 Feb 08:56:08 - [info] Node-RED version: v0.18.3
18 Feb 08:56:08 - [info] Node.js  version: v6.11.0
18 Feb 08:56:08 - [info] Linux 4.4.50 arm LE
18 Feb 08:56:09 - [info] Loading palette nodes
18 Feb 08:56:15 - [warn] ------------------------------------------------------
18 Feb 08:56:15 - [warn] [node-red-contrib-home-assistant/server] SyntaxError: Unexpected identifier
18 Feb 08:56:15 - [warn] [node-red-contrib-home-assistant/server-events] SyntaxError: Unexpected identifier
18 Feb 08:56:15 - [warn] [node-red-contrib-home-assistant/server-state-changed] SyntaxError: Unexpected identifier
18 Feb 08:56:15 - [warn] [node-red-contrib-home-assistant/trigger-state] SyntaxError: Unexpected identifier
18 Feb 08:56:15 - [warn] [node-red-contrib-home-assistant/poll-state] SyntaxError: Unexpected identifier
18 Feb 08:56:15 - [warn] [node-red-contrib-home-assistant/api-call-service] SyntaxError: Unexpected identifier (line:2)
18 Feb 08:56:15 - [warn] [node-red-contrib-home-assistant/api-current-state] SyntaxError: Unexpected identifier (line:1)
18 Feb 08:56:15 - [warn] [node-red-contrib-home-assistant/api-get-history] SyntaxError: Unexpected identifier (line:2)
18 Feb 08:56:15 - [warn] [node-red-contrib-home-assistant/api-render-template] SyntaxError: Unexpected identifier (line:2)
18 Feb 08:56:15 - [warn] ------------------------------------------------------
18 Feb 08:56:15 - [info] Settings file  : /share/node-red/settings.js
18 Feb 08:56:15 - [info] User directory : /share/node-red
18 Feb 08:56:15 - [warn] Projects disabled : set editorTheme.projects.enabled=true to enable
18 Feb 08:56:15 - [info] Flows file     : /share/node-red/flows.json
18 Feb 08:56:15 - [info] Creating new flow file
18 Feb 08:56:15 - [info] Starting flows
18 Feb 08:56:15 - [info] Started flows
18 Feb 08:56:15 - [info] Server now running at http://127.0.0.1:1880/`

**Comment by wizzor** [comment] 2018-02-18 08:53
I started doing a brand new installation today, and also cannot get any of the nodes to appear. On HASS.io 0.63.2 NodeRed extension 0.1.8

All of the nodes in the manage palette view show up as gray.

**Comment by jmesberg** [comment] 2018-02-18 12:36
I had same issue. Try stopping node-red, restarting, and then repeat the cycle one more time: update nodes, stop node-red, restart. That worked for me. Btw I had this same problem with other nodes I updated yesterday at same time so I don’t think the problem is specific to the home assistant nodes. 

John

**Comment by Bodge-IT** [comment] 2018-02-18 14:40
+1 on this issue from me too.
Tried @jmesberg suggestions to no avail.
Node-red 18.3
Homeassitant Node 0.3

**Comment by Joentje** [comment] 2018-02-18 16:25
Also having this issue. Tried a fresh installion of Node-red, but that didn't help.
Node-red: 18.3
node-red-contrib-home-assistant: 0.3.0

When I install 0.2.1 it works in node-red 18.3

**Comment by Resterday** [comment] 2018-02-18 17:02
I am having this issue too. Just trying to get started with Node-Red and Home Assistant. I have Hassio with the node-red add-on. When I install node-red-contib-home-assistant I get the following:

18 Feb 11:51:04 - [warn] [node-red-contrib-home-assistant/server] SyntaxError: Unexpected identifier
18 Feb 11:51:04 - [warn] [node-red-contrib-home-assistant/server-events] SyntaxError: Unexpected identifier
18 Feb 11:51:04 - [warn] [node-red-contrib-home-assistant/server-state-changed] SyntaxError: Unexpected identifier
18 Feb 11:51:04 - [warn] [node-red-contrib-home-assistant/trigger-state] SyntaxError: Unexpected identifier
18 Feb 11:51:04 - [warn] [node-red-contrib-home-assistant/poll-state] SyntaxError: Unexpected identifier
18 Feb 11:51:04 - [warn] [node-red-contrib-home-assistant/api-call-service] SyntaxError: Unexpected identifier (line:2)
18 Feb 11:51:04 - [warn] [node-red-contrib-home-assistant/api-current-state] SyntaxError: Unexpected identifier (line:1)
18 Feb 11:51:04 - [warn] [node-red-contrib-home-assistant/api-get-history] SyntaxError: Unexpected identifier (line:2)
18 Feb 11:51:04 - [warn] [node-red-contrib-home-assistant/api-render-template] SyntaxError: Unexpected identifier (line:2)

Is there a way I can install a previous version until a solution is found?

**Comment by wizzor** [comment] 2018-02-18 17:27
I tried various restart-reinstall cycles as well as installing several other addons, which worked as expected, so far no help.

**Comment by Joentje** [comment] 2018-02-18 17:48
@Resterday I removed the installed version using the GUI en then installed an older version using the cli.
 npm install node-red-contrib-home-assistant@0.2.1

**Comment by Resterday** [comment] 2018-02-18 18:02
@Joentke thanks for the response. I don't think I have access to npm with my setup: hass.io with node-red installed as an add-on. I can see the npm commands in the node-red add-on logs, but I don't know where I would input them myself. If you know how I could accomplish this that would be a big help.

**Comment by Joentje** [comment] 2018-02-18 18:18
I don't use hass.io setup myself. But in the hass.io setup, all are docker containers, so you can exec to that container. The only thing I don't know where the node_modules folder is. If you can locate that, you only need to perform that npm command. 
Some steps:

- first uninstall using the GUI the 0.3 version
- docker exec -it {nodred-container} bash
- cd /path/to/node_modules
- npm install node-red-contrib-home-assistant@0.2.1
- maybe restart

Don't know if it is the best way, but I guess it will work.

**Comment by flamingm0e** [comment] 2018-02-18 18:29
>so you can exec to that container

You sure about that?  Resin-OS is not a normal Linux distro.

**Comment by Bodge-IT** [comment] 2018-02-18 19:34
0.21 worked for me.
My setup has node-red as seperate install on pi rather than an addon in hass.io.

**Comment by AYapejian** [comment] 2018-02-19 15:09
Hey all, I suspsect that the issues seen here stem from the version of node being run on the node-red server / container.  Can you please list output of `node -v` from the server or inside the container?

This project has a docker build included and everything is working there so something must be different with the environments on the failing installs.

**Comment by impulz** [comment] 2018-02-19 15:22
Hey AYapejian,
I'm still at work so I can't check it our locally but according to the log the hass.io-Addon of node-red uses Node.js version: v6.11.0. 

best regards

**Comment by walthowd** [comment] 2018-02-19 15:39
Node 8.9.2, npm 5.5,1, Node-RED 0.18.3, did an in place upgrade from 0.21 to 0.30 without any issues.

**Comment by AYapejian** [comment] 2018-02-19 15:40
Ok, yea that confirms what I was thinking.  So some of the code I have written requires ES features not available until node 8.x.  Since v8.9 is the latest LTS version of node I thought it a safe bet this group would be up to date.  I do not use Hass.io personally so I can't comment on what to do there directly, however you can always take the Dockerfile found in this repo and adapt it to your needs and just run that.

**Comment by walthowd** [comment] 2018-02-19 15:42
@NotoriousBDG Might need an update to your hass.io addon if possible, see above. Many thanks.

**Comment by Bodge-IT** [comment] 2018-02-19 17:11
```
node -v:
v6.12.3
```

**Comment by Resterday** [comment] 2018-02-19 18:03
Any ideas for workaround for hassio users? I don't know that I could get node-red working as  standalone on a different pi since my home assistant is encrypted via duckdns add-on for hassio.

**Comment by impulz** [comment] 2018-02-19 19:10
Just a small note: @notoriousbdg's addon uses the official node-red docker image which is still using nodejs 6 (https://github.com/node-red/node-red-docker/blob/master/latest/Dockerfile), however they are currently planning to upgrade to nodejs 8 (https://github.com/node-red/node-red-docker/issues/62) at which point 0.3.0 should work within hass.io.

**Comment by Bodge-IT** [comment] 2018-02-19 22:08
Took me a while but I finally figured out I needed to update node.
The script here: [from Rasberry Pi docs](https://nodered.org/docs/hardware/raspberrypi) didn't seem to do it.
I then used:
`sudo npm cache clean -f
sudo npm install -g n
sudo n stable`
[from this stack](https://stackoverflow.com/questions/8191459/how-do-i-update-node-js)
Which gave me this issue:
`npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module 'internal/util/types'`
to which I had to run this:
`rm -rf /usr/local/lib/node_modules/npm `

And then re-ran the script from [from Rasberry Pi docs](https://nodered.org/docs/hardware/raspberrypi)

And I think then had to run the 3 sudo commands (above) again, before I finally got a working install.

A good result in the end because it's brought all my nodes into .node-red which is better, I has some globally installed from historic.

home-assistant v 0.3.0 running ok
npm 5.6.0
node 8.9.4
nr 18.3

**Comment by flamingm0e** [comment] 2018-02-20 03:02
yeah, official node-red docker node version is v6.12.3.  I am not using hassio, I run my own docker stack, and this is the latest version of node-red-docker.

**Comment by AYapejian** [comment] 2018-02-20 20:05
Just FYI for those that are running there own docker stacks as @flamingm0e mentions.  This project has an example [Dockerfile](https://raw.githubusercontent.com/AYapejian/node-red-contrib-home-assistant/master/_docker/node-red/Dockerfile) as well as an example [docker-compose.yaml](https://raw.githubusercontent.com/AYapejian/node-red-contrib-home-assistant/master/_docker/docker-compose.yml) file that I use for testing these nodes, node-red and home-assistant all integrated.  

I apologize for the problems, I don't use hassio and run my own custom images so didn't realize both node-red docker and the hassio addon are on non-latest LTS versions.  Hopefully those projects can update soon or the above mentioned files can provide a jumping point if you just want to build your own image.  Alternatively you always have the option of just staying at 0.2.x until those images are updated.  Sorry again all.

**Comment by notoriousbdg** [comment] 2018-02-20 20:32
I've committed a workaround to the issue with the hassio addon at https://github.com/notoriousbdg/hassio-addons/commit/c39fa4d497e90208f8d24085d9b5aae492614bf8.  For hassio users, updating the addon should get node-red-contrib-home-assistant working again.

**Comment by hipitihop** [comment] 2018-02-21 02:51
I can confirm the breakage on my docker stack and that switching back to 0.2.x solves the issue as an interim

**Comment by AYapejian** [comment] 2018-02-21 15:00
Think this one is nailed down and addressed a couple different ways, thanks @notoriousbdg for taking the initiative on that PR.

**Closed by AYapejian** 2018-02-21 15:00 UTC
Labels: question

**Comment by flamingm0e** [comment] 2018-02-22 14:00
Well that seems unfortunate for those of us that do NOT use hassio, and prefer to run official docker containers...I guess I will have to wait then.

**Comment by AYapejian** [comment] 2018-02-23 02:52
Sorry, @flamingm0e I didn't think it was asking all that much since spinning up a modified Docker image is pretty trivial. I just don't see removing the offending code to support the older of the two LTS's at this stage.

For anyone else wanting a more complete example than what I provided in this repository already of the Dockerfile see below:

1. Create a file called `Dockerfile`
2. Paste in these contents:
```dockerfile
FROM node:8.9.4

RUN mkdir -p /app /data && chown -R node:node /data /app

# Install NodeRed base app
ENV HOME=/app
USER node
WORKDIR /app
RUN npm install node-red@0.18.2

# Add Useful Automation Nodes here
RUN npm install                         \
    node-red-contrib-bigstatus

# Install node-red-contrib-home-assistant
RUN npm install AYapejian/node-red-contrib-home-assistant#master

# User configuration directory volume
EXPOSE 1880

# Environment variable holding file path for flows configuration
ENV NODE_PATH=/app/node_modules:/data/node_modules
CMD ["node", "node_modules/node-red/red.js", "--userDir", "/data", "-v", "flows.json"]


```

3. Create a file called `build-and-start.sh` and paste below. ( Change the first line below to wherever your flows are located on the host system )
```shell
#!/bin/sh
local_flows_dir=/tmp/node-red-flows

docker rm -f my-local-node-red
docker build -t local-node-red .
docker run -d --name my-local-node-red \
    --name my-local-node-red    \
    -p 1880:1880                \
    -v $local_flows_dir:/data    \
    local-node-red
```
4. Run `chmod a+x build-and-start.sh`
5. Run `./build-and-start.sh`
6. Hit `http://localhost:1880` in your browser
7. profit

**Comment by flamingm0e** [comment] 2018-03-02 04:29
looks like the node-red guys put out a tagged V8 image, but unfortunately I have to re-do all my flows :(  I built everything around the pre 0.3.0 and a lot of stuff doesn't work now.

**Comment by gregg098** [comment] 2018-03-19 18:12
I ran into this issue and fixed it by pulling the v8 image that flamingm0e mentioned. I also had a lot of flows randomly work and not work. I ended up re-creating all of my Hass nodes with the same information and now they work. Everything appears to work correctly and looks identical on upgrade, but there must be something behind the scenes that makes 0.2.1 and earlier flows not work all the time.

Can we get breaking changes notes for new version in the future?

**Comment by bbrendon** [comment] 2018-04-26 17:40
Shouldn't the latest by v8? LoL

**Comment by jncanches** [comment] 2018-07-26 00:16
Hi guys!
Running a 0.3.2 node-red-contrib-home-assistant on an hassbian freshly installed.
I have copied my node using import function of node-red and all my get current state nodes log "local state cache missing, sending empty payload". 
Of course those nodes break the flow :(

I have spent hours searching how to correct that :(
