### ISSUE TITLE
Doesn't work with Home Assistant 0.65.5

### ISSUE THREAD

**Issue by forhuan** [AYapejian/node-red-contrib-home-assistant#52] opened 2018-03-18 09:37 UTC
Cannot GET /homeassistant/entities

it seems that the rest_api has changed ?

https://home-assistant.io/developers/rest_api/

**Comment by Spartan-II-117** [comment] 2018-03-18 21:48
Was this working before? I had a similar issue when I first got started, unfortunately i don't remember how I solved it, however, I can tell you that it is working on my docker install of 0.65.5

**Comment by forhuan** [comment] 2018-03-18 23:48
No. I tried to replace /homeassistant/xxx to /api/xxx in node_modules,  but it still not work :(

**Comment by gregg098** [comment] 2018-03-19 18:08
I had this problem after I updated the Home Assistant Node Red module to 0.30. It turned out that this version of the module needs NodeJS >8.0. I'm using docker and had to change my docker compose file to pull the v8 image of Node Red.

**Comment by lamiskin** [comment] 2018-03-25 11:53
First time node-red user here, after taking a while to figure out I needed the v8 docker image to get going, I've now run in to a similar issue where node-red states it cannot get `Cannot GET /homeassistant/services`.

Confirmed home assistant is reachable by using curl within the container.

Running version 0.65.5 of home assistant.

**Comment by foobazbar123** [comment] 2018-03-26 19:46
Concur. This is no longer compatible with HA

**Comment by gregg098** [comment] 2018-03-26 20:07
It is definitely compatible. I'm running the V8 container and using https://xxxxx.duckdns.org:8123 as my server address with no issues. Did you add everything then deploy? Sometimes you will get that "Cannot get...." message before the first deploy.

**Comment by foobazbar123** [comment] 2018-03-26 21:00
Okay, I'm confused. I nuked the HA config I had done in node-red and redid it. Now it's happy. So, it appears you're correct in that it is compatible but I think changing the error message or something is in order?

**Comment by webxl** [comment] 2018-03-26 23:45
I was having an issue as well until I added the Content-Type header (PR:  https://github.com/AYapejian/node-home-assistant/pull/3) and made sure that the hostname in the server config matched HA's http -> base_url setting.

I'm not sure which actually got me up and running, but do the latter and perhaps the former won't be necessary, although the API calls should probably match the REST API docs.

**Comment by gsbrown** [comment] 2018-03-26 23:48
I am on Hassio 0.65.6 and Node Red 0.18.4 and am running into the same `Cannot GET /homeassistant/services` error. Is there a way to update to NodeJS 8.0 in Hassio, or am I stuck until the addon gets updated?

**Comment by foobazbar123** [comment] 2018-03-26 23:53
@gsbrown Same thing that happened for me. That error, nothing would fix it, then poof.. started working

**Comment by lamiskin** [comment] 2018-03-27 09:10
Apologies for the fuss, I wasn't aware that a flow needed deploying before it will retrieve some information from home assistant. Confirmed working now 👍

**Comment by skylord123** [comment] 2018-04-02 19:43
I also was getting issues until I removed `base_url` from my home assistant config.

**Comment by skylord123** [comment] 2018-04-04 18:08
@tedstriker are you connecting to another docker container on the same machine? (node-red running in docker as well as home assistant). I notice I have to set the internal IP of my host machine (given by my router) into the docker container otherwise it can't connect to home assistant (localhost on my docker container points to the container not the host machine).

**Comment by tedstriker** [comment] 2018-04-04 18:32
@skylord123 home assistant is running on a Pi and I can also receive events, etc. in nodered but when I open the state event node I receive two `Cannot GET /homeassistant/entities` error messages.

**Comment by Spartan-II-117** [comment] 2018-04-21 23:50
@nibotg did you get your issue firured out? you need to use the IP address of the computer instead of localhost or 127.0.0.1:8123 since within a container, those refer back to the same container.

@forhuan can this be closed?

**Comment by s3Pol** [comment] 2018-04-22 18:53
I'm having the same issue (Cannot GET /homeassistant/entities).
Already tried to change the file ha-api.js to add the Content-Type, HA config with base_url and without, NodeRed Base Url with localhost, 127.0.0.1, local ip...
With curl the api return {"message": "API running."}.
Any tips?

ENV::
Raspbian
Home Assistant 0.68.0.dev0
Node-RED version: v0.18.4
Node.js  version: v9.10.1
node-red-contrib-home-assistant 0.3.0

**Comment by nibotg** [comment] 2018-04-22 19:00
Hi @Spartan-II-117, no I'm afraid I didn't. I am using the IP address of the Synology nas but still get the same message. Any ideas appreciated please!

**Comment by nibotg** [comment] 2018-04-29 20:01
@skylord123, no, I had been using the latest version. I've just switched to v8 (installed through the DSM GUI) and it works! Many thanks for your help.

**Comment by Spartan-II-117** [comment] 2018-05-03 20:34
@kimmeld  can you write a PR to correct this?

**Comment by gregg098** [comment] 2018-05-03 20:48
@kimmeld 
I'm running Node Red in Docker (V8 image). My old configuration was using DuckDNS with LetsEncrypt. My Hass address was https://xxxx.duckdns.org:8123.  Now I use NGINX to deal with external connections and use http://ipaddress:8123 for my NodeRed URL since its on the same network. Both configurations worked flawlessly.  What I'm saying is that I could make an assumption those two configurations cover at least 90% of the Home Assistant community who uses Node Red successfully. If you are having some kind of issue that requires you to change the source code of Node Red, there is some other issue going on in your setup. I would recommend posting specific information about your configuration because you are going to fight this problem every time a new version comes out. I don't think a PR is justified here because the issues seem fairly isolated.

**Comment by kimmeld** [comment] 2018-05-03 21:35
@gregg098 What version of Home Assistant were you using?  I get the impression from my research into this problem that they changed where their API endpoint is located.

I didn't make changes to Node-RED itself, only minor changes to a handful of files in node-red-contrib-home-assistant to make some URLs match what Home Assistant is expecting.

@Spartan-II-117 I'll see what I can do.

**Comment by AYapejian** [comment] 2018-05-04 00:46
No worries.  I think I'm going to close this issue as the thread is pretty disjointed and I believe everything discussed here has been environment related.  If anyone is having issues still please open a specific issue with details or file a bug.

**Closed by AYapejian** 2018-05-04 00:46 UTC

**Comment by davidpadbury** [comment] 2018-05-06 20:29
I also hit this problem and haven't yet worked out the cause. From placing a few `console.log`s around, I believe that the `/homeassistant/entities` routes aren't being loaded by node-red, so when the UI hits them we see the 404.

However the nodes themselves can seem to use data from home-assistant just fine, so the problem appears to be limited to just this route registration.

Any suggestions for how to investigate further? I don't know node-red well. When should [these routes](https://github.com/AYapejian/node-red-contrib-home-assistant/blob/master/nodes/config-server/config-server.js#L42-L45) be loaded?

```
Node-RED version: v0.18.4
node-red-contrib-home-assistant: v0.3.2
Node.js  version: v9.11.1
```

**Comment by schford** [comment] 2018-06-25 11:41
I think it is to do with when you change    the below- if you change http route then it no longer pulls the data form home assistant - anyone got any ideas?  I need to change the http root to be able to reverse proxy with lets encrypt

 // The following property can be used in place of 'httpAdminRoot' and 'httpNodeRoot',
    // to apply the same root to both parts.
    //httpRoot: '/node-red',

**Comment by schford** [comment] 2018-06-25 12:07
On line 47 of server-events-state-changed.html - we can see the url it fetches to show entities, as it does not take into account httpRoot variable I have done a quick and dirty hard code - I am sure there must be a better way of fixing this but I am not a coder :-( as you can see below all I have done is manually put in the additional info for my installation.

                    $.get('/node-red/homeassistant/entities').done((entities) => {
