### ISSUE TITLE
 [api-call-service] SyntaxError: Unexpected token = (line:3)

### ISSUE THREAD

**Issue by prometrix** [AYapejian/node-red-contrib-home-assistant#6] opened 2017-11-26 20:05 UTC
Welcome to Node-RED
===================

26 Nov 20:53:22 - [info] Node-RED version: v0.17.5
26 Nov 20:53:22 - [info] Node.js  version: v4.2.6
26 Nov 20:53:22 - [info] Linux 4.4.0-62-generic x64 LE
26 Nov 20:53:22 - [info] Loading palette nodes
26 Nov 20:53:23 - [warn] ------------------------------------------------------
26 Nov 20:53:23 - [warn] [rpi-gpio] Info : Ignoring Raspberry Pi specific node
26 Nov 20:53:23 - [warn] [api-call-service] SyntaxError: Unexpected token = (line:3)
26 Nov 20:53:23 - [warn] [api-current-state] SyntaxError: Unexpected token {
26 Nov 20:53:23 - [warn] [api-get-history] SyntaxError: Unexpected token = (line:2)
26 Nov 20:53:23 - [warn] [api-render-template] SyntaxError: Unexpected token = (line:2)
26 Nov 20:53:23 - [warn] [server] SyntaxError: Unexpected token =
26 Nov 20:53:23 - [warn] [server-events] SyntaxError: Unexpected token = (line:2)
26 Nov 20:53:23 - [warn] [server-state-changed] SyntaxError: Unexpected token {
26 Nov 20:53:23 - [warn] ------------------------------------------------------
26 Nov 20:53:23 - [info] Settings file  : /home/erik/.node-red/settings.js
26 Nov 20:53:23 - [info] User directory : /home/erik/.node-red
26 Nov 20:53:23 - [info] Flows file     : /home/erik/.node-red/flows_ubuntu.json
26 Nov 20:53:23 - [info] Server now running at http://127.0.0.1:1880/
26 Nov 20:53:23 - [info] Waiting for missing types to be registered:
26 Nov 20:53:23 - [info]  - server
26 Nov 20:53:23 - [info]  - api-call-service
26 Nov 21:01:12 - [info] Stopping flows
26 Nov 21:01:12 - [info] Stopped flows
26 Nov 21:01:12 - [info] Waiting for missing types to be registered:
26 Nov 21:01:12 - [info]  - server
26 Nov 21:01:12 - [info]  - api-call-service

**Comment by AYapejian** [comment] 2017-12-04 04:18
This looks like it could be due to data you're passing into the API node.  Maybe I can improve / add validity checks if they aren't there already.  Could you provide some more details on how the flow was configured within node-red?

**Comment by trantoriana** [comment] 2017-12-07 18:00
This seems to be the underlying issue:

26 Nov 21:01:12 - [info] Waiting for missing types to be registered:
26 Nov 21:01:12 - [info] - server
26 Nov 21:01:12 - [info] - api-call-service

I have installed the addon in node-red, and upon refreshing the page I get exactly the same types to be missing. Deployment fails after that.

If I then reboot node-red (as instructed) none of the addon types are available anymore. They are available in the addons page, so it is installed. But the nodes are not available from the workflow pallet nor are the recognized once embedded in a flow already.

Perhaps something is missing from the latest release ?

**Comment by robvh84** [comment] 2018-01-03 16:15
I've installed node-red today and have the same issue. After installing node-red I installed node-red-contrib-home-assistant and after starting node-red I got the following output;

`3 Jan 17:11:51 - [info] Node-RED version: v0.17.5
3 Jan 17:11:51 - [info] Node.js  version: v4.7.2
3 Jan 17:11:51 - [info] Linux 4.10.0-42-generic x64 LE
3 Jan 17:11:51 - [info] Loading palette nodes
3 Jan 17:11:52 - [warn] ------------------------------------------------------
3 Jan 17:11:52 - [warn] [rpi-gpio] Info : Ignoring Raspberry Pi specific node
3 Jan 17:11:52 - [warn] [api-call-service] SyntaxError: Unexpected token = (line:3)
3 Jan 17:11:52 - [warn] [api-current-state] SyntaxError: Unexpected token {
3 Jan 17:11:52 - [warn] [api-get-history] SyntaxError: Unexpected token = (line:2)
3 Jan 17:11:52 - [warn] [api-render-template] SyntaxError: Unexpected token = (line:2)
3 Jan 17:11:52 - [warn] [server] SyntaxError: Unexpected token =
3 Jan 17:11:52 - [warn] [server-events] SyntaxError: Unexpected token = (line:2)
3 Jan 17:11:52 - [warn] [server-state-changed] SyntaxError: Unexpected token {
3 Jan 17:11:52 - [warn] ------------------------------------------------------
3 Jan 17:11:52 - [info] Settings file  : /home/node-red/.node-red/settings.js
3 Jan 17:11:52 - [info] User directory : /home/node-red/.node-red
3 Jan 17:11:52 - [info] Flows file     : /home/node-red/.node-red/flows_HASS01.json
3 Jan 17:11:52 - [info] Creating new flow file
3 Jan 17:11:52 - [info] Starting flows
3 Jan 17:11:52 - [info] Started flows
3 Jan 17:11:52 - [info] Server now running at http://127.0.0.1:1880/
`

When I insert a Home Assistant node in the flow an configure the server I get an error in the webinterface `Cannot GET /homeassistant/entities`.

In node-red I see:

`3 Jan 17:13:45 - [info] Installing module: node-red-contrib-home-assistant, version: 0.2.0
3 Jan 17:13:46 - [info] Installed module: node-red-contrib-home-assistant
3 Jan 17:13:46 - [info] Added node types:
3 Jan 17:13:46 - [info]  - node-red-contrib-home-assistant:api-call-service : SyntaxError: Unexpected token = (line:3)
3 Jan 17:13:46 - [info]  - node-red-contrib-home-assistant:api-current-state : SyntaxError: Unexpected token {
3 Jan 17:13:46 - [info]  - node-red-contrib-home-assistant:api-get-history : SyntaxError: Unexpected token = (line:2)
3 Jan 17:13:46 - [info]  - node-red-contrib-home-assistant:api-render-template : SyntaxError: Unexpected token = (line:2)
3 Jan 17:13:46 - [info]  - node-red-contrib-home-assistant:server : SyntaxError: Unexpected token =
3 Jan 17:13:46 - [info]  - node-red-contrib-home-assistant:server-events : SyntaxError: Unexpected token = (line:2)
3 Jan 17:13:46 - [info]  - node-red-contrib-home-assistant:server-state-changed : SyntaxError: Unexpected token {`

And after trying to deploy the flow;
`3 Jan 17:15:39 - [info] Stopping flows
3 Jan 17:15:39 - [info] Stopped flows
3 Jan 17:15:39 - [info] Waiting for missing types to be registered:
3 Jan 17:15:39 - [info]  - server
3 Jan 17:15:39 - [info]  - server-state-changed
`

**Comment by trantoriana** [comment] 2018-01-05 06:25
I migrated away from this addon to:

*) node-red-contrib-home-assistant-ws

no problems ever since.

**Comment by AYapejian** [comment] 2018-01-28 01:19
I still can't reproduce this however I did release 0.2.1 today, only an NPE fix really however there is an automated dev/test environment that may prove useful here.  Check the `README.md` on `master` if you're interested in giving it a go, details at the bottom.  You'll need Docker and Docker Compose installed but after that should be a 1 command spin up of HA/Node Red all configured and working OOTB.  If you can find steps to reproduce in that environment let me know and I'll troubleshoot.  Going to close this for now, feel free to reference in a new issue with repro steps in the dev environment however and I'll check it out asap.

**Closed by AYapejian** 2018-01-28 01:19 UTC
